### ISSUE TITLE
Cannot destructure undefined

### ISSUE THREAD

**Issue by gahabeen** [metalwarrior665/apify-utils#8]
Just had this error. Changed it to ` const { locked } = await this.store.getValue('LOCKED') || {};`

https://github.com/metalwarrior665/apify-utils/blob/a70869baa28f59fc6cb18d06e700b7aa5453a341/src/state-persistence.js#L249

Let me know if you want a PR @metalwarrior665

**Comment by metalwarrior665** [comment]
Thanks, fixed
